config/routes.rb
Rails.application.routes.draw do
  #get '/index', to: 'items#index'
  root to: "items#index"
  resources :items do # Стандартные маршруты RESTful
    # Для данных маршрутов есть acrtion_controllers: upvote и expensiv
    get :upvote, on: :member # запись дополнительного маршрута для единственного члена, участника, вида: /photos/:id/preview
    get :expensive, on: :collection # создаем дополнительный маршрут для коллекции элементов, маршрут вида: /items/expensive     
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :price, numericality: { greater_than: -1 }
  validates :name, :description, presence: true

  after_initialize  {p 'Инициализация'} # Item.new, Item.first, Item.last
  after_save        {p 'Сохранено'}     # Item.save, Item.create
  after_create      {p 'Создано'}       # Item.create
  after_update      {p 'Обновлено'}     # Item.update
  after_destroy    {p 'Удалено'}       # Item.last.destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def render_403
    # метод главного контроллера для вывода страницы 403 (доступ запрещен или status: :forbidden)
    render file: 'public/403.html', status: :forbidden # рендер файла 403 (Rails сделает это и без этой записи)
  end

  def render_404
    # метод главного контроллера для вывода страницы 404 (страница не найдена или status: 404)
    render file: 'public/404.html', status: :not_found  # рендер файла 404 (Rails сделает это и без этой записи)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #layout false
  #skip_before_action :verify_authenticity_token

  # перед выполнение action: show, edit, update, destroy вызывает метод find_item 
  # из которого возвращается найденный элемент модели item  
  before_action :find_item, only: %i[show edit update destroy upvote]
  # для контроллеров new..destroy проходит предварительную проверку на наличие admin в params
  before_action :admin?, only: %i[destroy] # new create edit update добавить в [] по необходимости
  after_action :information, onli: [:index] # вызывается после выполнения action-а index

  def index
    @items = Item.all.sort_by {|key| key[:id]} # Все элементы из таблицы Items сортируем по ключу :id элементов
  end

  def new
    @item = Item.new
  end

  def upvote # метод дял голосования
    @item.increment! :votes_count # увеличить число по ключу votes_count на 1
    redirect_to items_path
  end

  def expensive
    @items = Item.where('price > 50') # price: > 50 не заработало бы, поэтому формляется, как запрос SQL в виде строки
    render :index # отрендерить представление view, без перезагрузки контроллера, если сделать redirect_to :index то он подгрузит контроллер index и переменной @items передадутся все элементы таблицы
  end

  def create
    if params[:name] == "Запись"
      item = Item.new(
        name: params[:name], 
        price: params[:price], 
        weight: params[:weight], 
        description: params[:description])
      item.save
      redirect_to items_path
    else
      item = Item.create(item_params)
      if item.persisted? # если item сохранен то
        redirect_to items_path # перееаправить на страницу всех объектов Item
      #render json: item.name, status: :created
      #render json: "Данные сохранены" # рендер в формате json
      else # если item не прошел валидацию и не сохранился
        render json: item.errors # рендер в формате json ошибки items
      end
    end    
  end

  def show
    # Rails переходит на метод show, после того, как перехватывает из браузера маршрут вида /items/:id где :id - номер записи в базе данных, и сохраняет этот id в хеше params для дальнейшего использования
    # Поиск записи в базе данных по id, переданного в хеше params. Сохраняет в переменной экземпляра массив с хешем данных найденного объекта                    
    # render body: "Страницы не существует", status: 404 unless @item # если @item нет выведет сообщение об ошибке
  end

  def edit; end # краткая запись, если вызов идет на предствление или нет кода внутри метода

  def update        
    if @item.update(item_params)
      redirect_to item_path
    else
      render json: item.errors, status: :unprocessable_entity # необработанный объект
    end 
  end

  def destroy    
    if @item.destroy.destroyed?    
      redirect_to items_path
    else
      render json: item.errors, status: :unprocessable_entity # необработанный объект
    end    
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :weight, :description)
    #params.permit(:name, :price, :weight, :description)
  end

  def find_item
    @item = Item.where(id: params[:id]).first # найти элемнт, где id = params.id первый из списка
    #@item = Item.find(params[:id])
    render_404 unless @item # рендерит метод главного контроллера render_404 если @item не найден    
  end

  def admin? # приватный метод для проверки на админа (вызывается из before_action)
    #true
    # если в строке браузера передать дополнительную ключ в paramsс в виде ?admin=1
    # то доступ будет открыт, в противном случае выведет сообщение "Доступ запрещен"    
    #render json: 'Доступ запрещен', status: :forbidden unless params[:admin]
    render_403 unless params[:admin]
  end

  def information
    puts "Страница загружена"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h2>Редактирование записи: <%= @item.id %>. <%= @item.name %></h2>

<%= form_with model: @item do |form| %>
	<%= form.label :name, "Название продукта:" %>
	<%= form.text_field :name %>
	<br>
	<%= form.label :price, "Цена:" %>
	<%= form.text_field :price %>
	<br>
	<%= form.label :weight, "Вес:" %>
	<%= form.text_field :weight %>
	<br>
	<%= form.label :description, "Описание:" %>
	<%= form.text_field :description %>
	<br><br>
	<%= form.submit "Сохранить"%>
	<%= link_to "Назад", item_path(@item) %>
<% end %>

app/views/items/index.html.erb
<h2>Все записи таблицы items</h2>

<table>
<tr>
	<th>№</th>
	<th>Наименование</th>
	<th>Цена</th>
	<th>Вес</th>
	<th>Описание</th>
	<th>Рейтинг</th>
	<th>Редактирование</th>
	<th>Удаление</th>
</tr>

<% @items.each do |item| %>
	<tr>
		<td><%= item.id %></td>
		<td><%= link_to item.name, item_path(item) %></td>
		<td><%= item.price %></td>
		<td><%= item.weight %></td>
		<td><%= item.description %></td>
		<td><%= item.votes_count %> <%= link_to "+", upvote_item_path(item) %></td>
		<td><%= link_to "Редактировать", edit_item_path(item) %></td>
		<td><%= link_to "Удалить", item_path(item), method: :delete %></td>
	</tr>
<% end %>
</table>
<p><%= link_to "Добавить новую запись", new_item_path %></p>
<p><%= link_to "Быстрое добавление записи", items_path(:name => "Запись", :price => "200", :weight => "200", :description => "Описание"), method: :post %></p>
<p><%= link_to "Отобразить дорогие", expensive_items_path %></p>

app/views/items/new.html.erb
<h2>Добавить новую запись в таблицу items</h2>
<%= form_with model: @item do |form| %>
	<%= form.label :name, "Название продукта:" %>
	<%= form.text_field :name %>
	<br>
	<%= form.label :price, "Цена:" %>
	<%= form.text_field :price %>
	<br>
	<%= form.label :weight, "Вес:" %>
	<%= form.text_field :weight %>
	<br>
	<%= form.label :description, "Описание:" %>
	<%= form.text_field :description %>
	<br><br>
	<%= form.submit "Сохранить"%>
<% end %>
<%= link_to "Вернуться на главную", items_path %>

app/views/items/show.html.erb
<h2>Запись в таблице <%= @item.id %>. <%= @item.name %></h2>

<p>Наименование: <%= @item.name %>
<p>Цена: <%= @item.price %></p>
<p>Вес: <%= @item.weight %></p>
<p>Описание: <%= @item.description %></p>

<%= link_to "Назад", items_path %>
<%= link_to "Редактировать", edit_item_path %>
<%= link_to "Удалить", item_path(@item.id), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>    
  </head>

  <body>
    <%= yield %>
  </body>
</html>